version: '3.8'

services:
  bot:
    image: kosssst_link_bot:latest
    container_name: link-bot
    restart: unless-stopped
    volumes:
      - link-bot-config-volume:/link-bot/configs

volumes:
  link-bot-config-volume:
    driver: local
    driver_opts:
      type: none
      device: configs/
      o: bind
    